# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pruebaNW

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d7fb1be931bd4611b81124ad67952292 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d7bda02653d04c20802a68a26e6545c0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_d7fb1be931bd4611b81124ad67952292 }}/claudiotapiac/pruebaNW:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pruebaNW'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b04afbd2e91f4baa82c83fd1f97c2d2a }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_d7fb1be931bd4611b81124ad67952292 }}/claudiotapiac/pruebaNW:${{ github.sha }}'